package com.example.quizzard.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFF3BB81)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFffddba)
val md_theme_light_onPrimaryContainer = Color(0xff642900)
val md_theme_light_secondary = Color(0xFF875200)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFffddba)
val md_theme_light_onSecondaryContainer = Color(0xFF2b1700)
val md_theme_light_tertiary = Color(0xFF875200)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFffddba)
val md_theme_light_onTertiaryContainer = Color(0xFF2b1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xffFBF5EE)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFBAC3FF)
val md_theme_light_surfaceTint = Color(0xFF4355B9)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val trueAnswer = Color(0xFF2E996D)
val falseAnswer = Color(0xFFEB8844)
